resources:
  repositories:

  - repository: MyGitHubRepo1 # The name used to reference this repository in the checkout step
    type: github
    endpoint: github.com_srkarana
    name: srkaranam/Test
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo $(platform)
      xxx

- script: dir $(Build.SourcesDirectory)
